# Generated by Django 4.1.4 on 2023-11-22 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='administrator_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('admin_id', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='profileimg')),
                ('password', models.CharField(max_length=100)),
                ('reenter_password', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='admin_login',
        ),
    ]
