# Generated by Django 4.1.4 on 2023-11-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_quiz', '0002_administrator_login_delete_admin_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator_login',
            name='image',
            field=models.ImageField(blank=True, upload_to='administrator_login/'),
        ),
    ]
