# Generated by Django 4.1.4 on 2023-11-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_quiz', '0003_alter_administrator_login_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator_login',
            name='email_id',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
