# Generated by Django 4.1.4 on 2023-12-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_quiz', '0004_administrator_login_email_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='administrator_signin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.EmailField(blank=True, max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
