# Generated by Django 4.1.4 on 2023-12-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_quiz', '0005_administrator_signin'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator_signin',
            name='admin_id',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
