# Generated by Django 4.1.4 on 2023-12-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_quiz', '0006_administrator_signin_admin_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrator_login',
            name='id',
        ),
        migrations.AlterField(
            model_name='administrator_login',
            name='email_id',
            field=models.EmailField(blank=True, max_length=254, primary_key=True, serialize=False),
        ),
    ]
