# Generated by Django 4.1.4 on 2023-12-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_quiz', '0008_administrator_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator_questions',
            name='correct_answer',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
