# Generated by Django 4.1.4 on 2023-12-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_quiz', '0009_administrator_questions_correct_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrator_questions',
            name='id',
        ),
        migrations.AlterField(
            model_name='administrator_questions',
            name='correct_answer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='administrator_questions',
            name='question',
            field=models.CharField(default='question', max_length=500, primary_key=True, serialize=False),
        ),
    ]
