# Generated by Django 4.1.4 on 2023-12-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_quiz', '0010_remove_administrator_questions_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator_questions',
            name='question',
            field=models.CharField(default=None, max_length=500, primary_key=True, serialize=False),
        ),
    ]
