# Generated by Django 4.1.4 on 2023-12-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_quiz', '0011_alter_administrator_questions_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator_questions',
            name='correct_answer',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
