# Generated by Django 4.1.4 on 2023-12-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_quiz', '0012_alter_administrator_questions_correct_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator_questions',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
